'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property IIDCLIENTE As Integer
    Public Property NOMBRE As String
    Public Property APPATERNO As String
    Public Property APMATERNO As String
    Public Property EMAIL As String
    Public Property DIRECCION As String
    Public Property IIDSEXO As Nullable(Of Integer)
    Public Property TELEFONOFIJO As String
    Public Property TELEFONOCELULAR As String
    Public Property BHABILITADO As Nullable(Of Integer)
    Public Property bTieneUsuario As Nullable(Of Integer)
    Public Property TIPOUSUARIO As String

    Public Overridable Property Sexo As Sexo
    Public Overridable Property TIPOUSUARIOREGISTRO As TIPOUSUARIOREGISTRO
    Public Overridable Property VENTA As ICollection(Of VENTA) = New HashSet(Of VENTA)

End Class
