'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Lugar
    Public Property IIDLUGAR As Integer
    Public Property NOMBRE As String
    Public Property DESCRIPCION As String
    Public Property BHABILITADO As Nullable(Of Integer)

    Public Overridable Property Viaje As ICollection(Of Viaje) = New HashSet(Of Viaje)
    Public Overridable Property Viaje1 As ICollection(Of Viaje) = New HashSet(Of Viaje)

End Class
