'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RolPagina
    Public Property IIDROLPAGINA As Integer
    Public Property IIDROL As Nullable(Of Integer)
    Public Property IIDPAGINA As Nullable(Of Integer)
    Public Property BHABILITADO As Nullable(Of Integer)

    Public Overridable Property Pagina As Pagina
    Public Overridable Property Rol As Rol

End Class
