'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property IIDUSUARIO As Integer
    Public Property NOMBREUSUARIO As String
    Public Property CONTRA As String
    Public Property TIPOUSUARIO As String
    Public Property IID As Nullable(Of Integer)
    Public Property IIDROL As Nullable(Of Integer)
    Public Property bhabilitado As Nullable(Of Integer)

    Public Overridable Property Rol As Rol
    Public Overridable Property TIPOUSUARIOREGISTRO As TIPOUSUARIOREGISTRO

End Class
