'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VENTA
    Public Property IIDVENTA As Integer
    Public Property IIDCLIENTE As Nullable(Of Integer)
    Public Property TOTAL As Nullable(Of Decimal)
    Public Property FECHAVENTA As Nullable(Of Date)
    Public Property BHABILITADO As Nullable(Of Integer)

    Public Overridable Property Cliente As Cliente
    Public Overridable Property DETALLEVENTA As ICollection(Of DETALLEVENTA) = New HashSet(Of DETALLEVENTA)

End Class
