'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Viaje
    Public Property IIDVIAJE As Integer
    Public Property IIDLUGARORIGEN As Nullable(Of Integer)
    Public Property IIDLUGARDESTINO As Nullable(Of Integer)
    Public Property PRECIO As Nullable(Of Decimal)
    Public Property FECHAVIAJE As Nullable(Of Date)
    Public Property IIDBUS As Nullable(Of Integer)
    Public Property NUMEROASIENTOSDISPONIBLES As Nullable(Of Integer)
    Public Property BHABILITADO As Nullable(Of Integer)
    Public Property FOTO As Byte()
    Public Property nombrefoto As String

    Public Overridable Property Asiento As ICollection(Of Asiento) = New HashSet(Of Asiento)
    Public Overridable Property Bus As Bus
    Public Overridable Property DETALLEVENTA As ICollection(Of DETALLEVENTA) = New HashSet(Of DETALLEVENTA)
    Public Overridable Property Lugar As Lugar
    Public Overridable Property Lugar1 As Lugar

End Class
